### PR TITLE
Fixed twitter redirect and deleted riot api key!

### PR DESCRIPTION
**Pull request by Kreiseljustus**
DO NOT INCLUDE YOUR API KEY IN A PUBLIC REPO.

### CODE REVIEW

**Review by brkagithub — CHANGES_REQUESTED** [review]
the twitter button is supposed to bring you to a user's twitter account (while setting up your profile you are asked to enter your twitter **handle** not the url - so the url right now is correct).

about the riot.txt file it's not an api key but i completely forgot to delete it lol. so if you want remove the twitter change and ill approve the pull request (never accepted pull requests but from what i know its not possible to accept only one of the commits - not sure about it). also if you want to ask anything feel free to add on discord brka#6795

**Comment by Kreiseljustus** [comment]
Hey! So i checked again and it seems that the profile where i clicked on the Twitter SocialIcon had entered https://twitter.com/USERNAME as their handle and thats why i got redirected to https://twitter.com/https://twitter.com/USERNAME, so sorry if i wasted your time :D. Maybe you should implement somekind of check to verify that the handle is not a full domain?

**Comment by Kreiseljustus** [comment]
> Hey! So i checked again and it seems that the profile where i clicked on the Twitter SocialIcon had entered https://twitter.com/USERNAME as their handle and thats why i got redirected to https://twitter.com/https://twitter.com/USERNAME, so sorry if i wasted your time :D. Maybe you should implement somekind of check to verify that the handle is not a full domain?

Changed it back to the original now.

**Comment by brkagithub** [comment]
> Hey! So i checked again and it seems that the profile where i clicked on the Twitter SocialIcon had entered https://twitter.com/USERNAME as their handle and thats why i got redirected to https://twitter.com/https://twitter.com/USERNAME, so sorry if i wasted your time :D. Maybe you should implement somekind of check to verify that the handle is not a full domain?

will do that, thanks for the great suggestion, if you're interested in contributing more im adding things that are on the 'todo list' to the README file

**Pull request merged**
